/*
 * spi.h
 *
 *  Created on: Apr 9, 2025
 *      Author: Tigran
 */

#ifndef DRIVERS_SPI_SPI_H_
#define DRIVERS_SPI_SPI_H_

#define SPI_SIZE 4
#define SPI_READ 0x3
#define SPI_WRITE 0x2
#define SPI_WREN 0x6
#define SPI_WRDI 0x4

#include "main.h"
#include <stdbool.h>

enum {
	SPI_CLK_POLARITY_LOW = SPI_POLARITY_LOW,
	SPI_CLK_POLARITY_HIGH = SPI_POLARITY_HIGH,

	SPI_CLK_PHASE_1EDGE = SPI_PHASE_1EDGE,
	SPI_CLK_PHASE_2EDGE = SPI_PHASE_2EDGE,

	SPI_DATA_4BIT = SPI_DATASIZE_4BIT,
	SPI_DATA_5BIT = SPI_DATASIZE_5BIT,
	SPI_DATA_6BIT = SPI_DATASIZE_6BIT,
	SPI_DATA_7BIT = SPI_DATASIZE_7BIT,
	SPI_DATA_8BIT = SPI_DATASIZE_8BIT,
	SPI_DATA_9BIT = SPI_DATASIZE_9BIT,
	SPI_DATA_10BIT = SPI_DATASIZE_10BIT,
	SPI_DATA_11BIT = SPI_DATASIZE_11BIT,
	SPI_DATA_12BIT = SPI_DATASIZE_12BIT,
	SPI_DATA_13BIT = SPI_DATASIZE_13BIT,
	SPI_DATA_14BIT = SPI_DATASIZE_14BIT,
	SPI_DATA_15BIT = SPI_DATASIZE_15BIT,
	SPI_DATA_16BIT = SPI_DATASIZE_16BIT,

	SPI_BAUD_RATE_2 = SPI_BAUDRATEPRESCALER_2,
	SPI_BAUD_RATE_4 = SPI_BAUDRATEPRESCALER_4,
	SPI_BAUD_RATE_8 = SPI_BAUDRATEPRESCALER_8,
	SPI_BAUD_RATE_16 = SPI_BAUDRATEPRESCALER_16,
	SPI_BAUD_RATE_32 = SPI_BAUDRATEPRESCALER_32,
	SPI_BAUD_RATE_64 = SPI_BAUDRATEPRESCALER_64,
	SPI_BAUD_RATE_128 = SPI_BAUDRATEPRESCALER_128,
	SPI_BAUD_RATE_256 = SPI_BAUDRATEPRESCALER_256,

};

uint8_t spi_write(SPI_HandleTypeDef *hspix, uint16_t address, uint8_t data);
uint8_t spi_read(SPI_HandleTypeDef *hspix, uint16_t address, uint8_t *data);
uint8_t spi_read_bulk(SPI_HandleTypeDef *hspix, uint16_t address, uint8_t size, uint8_t *data);


#endif /* DRIVERS_SPI_SPI_H_ */
